// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using Kentico.Kontent.Delivery.Abstractions;

namespace CeramicsPortfolio.Blazor.Models
{
    public partial class Test1
    {
        public const string Codename = "test1";
        public const string BCodename = "b";
        public const string XCodename = "x";

        public string B { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string X { get; set; }
    }
}